// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillUp.DataAccessLayer.Data;

#nullable disable

namespace SkillUp.DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240930094425_AddImgUrlToCoursesTable")]
    partial class AddImgUrlToCoursesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillUp.DataAccessLayer.Entities.Courses", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalHours")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "This course is part of the Executive Data Science Specialization ,When you enroll in this course, you'll also be enrolled in this Specialization.1-Learn new concepts from industry experts 2-Gain a foundational understanding of a subject or tool 4-Develop job-relevant skills with hands-on projects 5-Earn a shareable career certificate",
                            ImgUrl = "",
                            InstructorName = "Jeff Leek",
                            Price = 3980f,
                            Title = "A Crash Course in Data Science",
                            TotalHours = 29f
                        },
                        new
                        {
                            ID = 2,
                            Description = "Blazor is an exciting new part of .NET Core (.NET 9) designed for building rich web user interfaces in C#. This course will help developers transition from building basic sample apps to implementing more real world concepts, design patterns, and features.",
                            ImgUrl = "",
                            InstructorName = "Bhrugen Patel",
                            Price = 1250f,
                            Title = "Blazor - The Complete Guide [.NET 9] [2024] [E-commerce]",
                            TotalHours = 12f
                        },
                        new
                        {
                            ID = 3,
                            Description = "Learn how to use Adobe Illustrator to draw fashion flats. Develop your skills to enable you to produce creative, accurate product designs quickly and to standards required for retail and manufacturing.",
                            ImgUrl = "",
                            InstructorName = "Jo Hughes",
                            Price = 300f,
                            Title = "Learn to draw fashion with Adobe Illustrator CC - Beginners",
                            TotalHours = 5f
                        },
                        new
                        {
                            ID = 4,
                            Description = "",
                            ImgUrl = "",
                            InstructorName = "Jonathan Peters",
                            Price = 800f,
                            Title = "Music Theory",
                            TotalHours = 8f
                        },
                        new
                        {
                            ID = 5,
                            Description = "This course will help you understand accounting, finance, financial modeling and valuation from scratch (no prior accounting, finance, modeling or valuation experience is required).\r\n\r\nBy the end of this course, you will also know how to value companies using several different valuation methodologies that I have used during my Wall Street career so you can come up with target prices for the companies that you are analyzing.",
                            ImgUrl = "",
                            InstructorName = "Chris Haroun",
                            Price = 2600f,
                            Title = "Introduction to Finance, Accounting, Modeling and Valuation",
                            TotalHours = 25f
                        },
                        new
                        {
                            ID = 6,
                            Description = "Discrete Mathematics (DM), or Discrete Math is the backbone of Mathematics and Computer Science. DM is the study of topics that are discrete rather than continuous, for that, the course is a MUST for any Math or CS student. The topics that are covered in this course are the most essential ones, those that will touch every Math and Science student at some point in their education. ",
                            ImgUrl = "",
                            InstructorName = "Miran Fattah",
                            Price = 1250f,
                            Title = "Discrete Mathematics",
                            TotalHours = 18f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
